name: List GCP Projects-2

on:
  workflow_dispatch:
    

jobs:
  list-projects:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
    
          service_account: gcs-githubactiions@airman1-429600.iam.gserviceaccount.com
          workload_identity_provider: projects/659578408596/locations/global/workloadIdentityPools/github-actions/providers/my-provider

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: List GCP Projects
        run: |
          gcloud projects list 
